version: 2
jobs:
  build:
    context: DockerHub
    docker:
      - image: circleci/buildpack-deps:focal
        auth:
          username: $docker_hub_user
          password: $docker_hub_pwd
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          IMAGE='tplcom/gitpod-drupal-workspace'
          TAG='latest'
          echo "$docker_hub_pwd" | docker login --username $docker_hub_user --password-stdin
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG