version: 2.1
orbs:
  docker: circleci/docker@1.7.0
workflows:
    deploy-docker-hub:
      jobs:
        - docker/publish:
            docker-password: PASSWORD
            docker-username: USER
            image: tplcom/gitpod-drupal-workspace 
            tag: latest 
            update-description: true 
            use-docker-credentials-store: true 
            use-remote-docker: true 