version: 2
jobs:
  build:
    context: DockerHub
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - run: |
          IMAGE='tplcom/gitpod-drupal-workspace'
          TAG='latest'
          docker build -t $IMAGE:$TAG .
          echo $docker_hub_pwd | docker login -u $docker_hub_user --password-stdin
          docker push $IMAGE:$TAG