version: 2
jobs:
  build:
    context: DockerHub
    docker:
      - image: tplcom/gitpod-drupal-workspace:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build . -t tplcom/gitpod-drupal-workspace
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $docker_hub_user -p $docker_hub_pwd
              docker push tplcom/gitpod-drupal-workspace:latest
            fi