version: 2.1
context: DockerHub
executors:
  circleci-executor:
    docker:
      - image: cimg/base:stable  
jobs:
  deploy-docker-image:
    executor: circleci-executor
    steps:
      - checkout
      - run: |
          IMAGE='tplcom/gitpod-drupal-workspace'
          TAG='latest
          docker build -t $IMAGE:$TAG .
          echo $docker_hub_pwd | docker login -u $docker_hub_user --password-stdin
          docker push $IMAGE:$TAG
workflows:
  docker-hub-workflow:
    jobs:
      - deploy-docker-image