version: 2
jobs:
  build:
    context: DockerHub
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          IMAGE='tplcom/gitpod-drupal-workspace'
          TAG='latest'
          docker login --username $docker_hub_user -p $docker_hub_pwd
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG