version: 2
jobs:
  build:
    context: DockerHub
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          IMAGE='tplcom/gitpod-drupal-workspace'
          TAG='latest'
          docker build -t $IMAGE:$TAG .
          echo $docker_hub_pwd | docker login -u $docker_hub_user --password-stdin
          docker push $IMAGE:$TAG